version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    depends_on:
      - "logstash"
    networks:
      - front-tier
      - back-tier
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
    depends_on:
      - "redis"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: elasticsearch
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks: 
      - log-tier

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    container_name: logstash
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro 
    networks:
      - log-tier

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    networks: 
      - log-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
  log-tier: